OP-22190: Upgrade Spinnaker 1.33.2
OpsMx/gate-oes pull request #60
Opened 2024-06-05 10:30 UTC by sudhakaropsmx

https://devopsmx.atlassian.net/browse/OP-22190

2024-06-06 11:56 UTC, aman-agrawal commented
why below files got deleted :
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/RetrofitConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/OidcConfigController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/NoopOidcConfigService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/OidcConfigService.java

2024-06-06 11:57 UTC, aman-agrawal commented
Pls resolve the conflicts.
Pls add testing details & pls mention what left on UT side.

2024-06-06 11:57 UTC, aman-agrawal commented
Verified few commits from sheet - LGTM

2024-06-06 11:57 UTC, aman-agrawal requested changes

2024-06-06 11:57 UTC, aman-agrawal commented on gate-iap/src/main/java/com/netflix/spinnaker/gate/security/iap/IapSsoConfig.java
> +  //  @Override
I dont see usage of it, can you pls verify relevance of these methods.
May be as a separate task (not a blocker for upgrade-1.33.x task)

2024-06-10 04:26 UTC, sudhakaropsmx commented on gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/KeelService.java
> +import com.netflix.spinnaker.gate.model.manageddelivery.*;
Removed * import and replaced with specific classes

2024-06-10 04:27 UTC, sudhakaropsmx commented on .github/workflows/gate-build-pr-base.yml
> +      - OES-1.30.x
Updated the version gate branch

2024-06-13 10:57 UTC, sudhakaropsmx commented
> why below files got deleted : gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/RetrofitConfig.groovy gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/OidcConfigController.java gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/NoopOidcConfigService.java gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/OidcConfigService.java

These are removed from the 1.33.2

2024-06-13 10:58 UTC, sudhakaropsmx commented on gate-iap/src/main/java/com/netflix/spinnaker/gate/security/iap/IapSsoConfig.java
> +  //  @Override
yes, these are not blockers these same as in 1.30.x

2024-06-24 11:18 UTC, sudhakaropsmx commented
> Pls resolve the conflicts. Pls add testing details & pls mention what left on UT side.

gate-web test case yet to verify other than this out of 70 1 failing

2024-06-25 11:41 UTC, sudhakaropsmx commented
> Pls resolve the conflicts. Pls add testing details & pls mention what left on UT side.
91 test cases 83 passed 8 failed

2024-06-27 16:26 UTC, j-sandy approved these changes
LGTM !

2024-07-03 08:22 UTC, sudhakaropsmx commented
> > Pls resolve the conflicts. Pls add testing details & pls mention what left on UT side.

![Screenshot from 2024-07-03 13-51-38](https://github.com/OpsMx/gate-oes/assets/48587497/d50ff37b-6327-4944-bb9c-1f0676849da0)

2024-07-03 11:57 UTC, merged